{
 "title": "CVAD Overview",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "SiteName",
    "query": "SHOW TAG VALUES WITH KEY = \"SiteName\""
   },
   {
    "name": "PROD",
    "query": "SHOW TAG VALUES WITH KEY = \"DeliveryGroupName\""
   },
   {
    "name": "DEV",
    "query": "SHOW TAG VALUES WITH KEY = \"DeliveryGroupName\""
   },
   {
    "name": "TEST",
    "query": "SHOW TAG VALUES WITH KEY = \"DeliveryGroupName\""
   },
   {
    "name": "TRAIN",
    "query": "SHOW TAG VALUES WITH KEY = \"DeliveryGroupName\""
   }
  ]
 },
 "panels": [
  {
   "title": "Total Sessions",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "query": "SELECT sum(\"activesessions\") AS \"Active\", sum(\"idlesessions\") AS \"Idle\", sum(\"disconnectedsessions\") AS \"Disconnected\", sum(\"othersessions\") AS \"Other\", sum(\"ActiveSessions\") AS \"Active\", sum(\"IdleSessions\") AS \"Idle\", sum(\"DisconnectedSessions\") AS \"Disconnected\", sum(\"OtherSessions\") AS \"Other\" FROM \"XdWorker\" WHERE (\"Host\" = '172.30.190.73' OR \"Host\" = '172.30.190.74' OR \"host\" = '172.30.190.73' OR \"host\" = '172.30.190.74') AND $timeFilter GROUP BY time(5m) fill(none)",
     "select": [
      [
       { "params": [ "ActiveSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Active" ], "type": "alias" }
      ],
      [
       { "params": [ "IdleSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "DisconnectedSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Disconnected" ], "type": "alias" }
      ],
      [
       { "params": [ "OtherSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Other" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" }
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "query": "SELECT sum(\"totalsessions\") AS \"Total\" FROM \"XdWorker\" WHERE (\"Host\" = '172.30.190.73' OR \"Host\" = '172.30.190.74' OR \"host\" = '172.30.190.73' OR \"host\" = '172.30.190.74') AND $timeFilter GROUP BY time(5m) fill(none)",
     "select": [
      [
       { "params": [ "TotalSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" }
     ]
    }
   ]
  },
  {
   "title": "Machines Unregistered",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_DeliveryGroupName",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "DeliveryGroupName" ], "type": "tag" },
      { "params": [ "SiteName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "Unregistered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Servers",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "Registered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Registered" ], "type": "alias" }
      ],
      [
       { "params": [ "Unregistered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Unregistered" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" }
     ]
    }
   ]
  },
  {
   "title": "DEV",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "ActiveSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Active" ], "type": "alias" }
      ],
      [
       { "params": [ "IdleSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "DisconnectedSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Disconnected" ], "type": "alias" }
      ],
      [
       { "params": [ "OtherSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Other" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$DEV$/" }
     ]
    }
   ]
  },
  {
   "title": "DEV Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_DeliveryGroupName - $tag_CatalogName $col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "CatalogName" ], "type": "tag" },
      { "params": [ "DeliveryGroupName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "LoadIndexMax" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "LoadIndexAvg" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$DEV$/" }
     ]
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "ActiveSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "IdleSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Avg Prod Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "LoadIndexAvg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$PROD$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Max Prod Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "LoadIndexMax" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" }
     ]
    }
   ]
  },
  {
   "title": "Disconnected",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "DisconnectedSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" }
     ]
    }
   ]
  },
  {
   "title": "TEST",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "ActiveSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Active" ], "type": "alias" }
      ],
      [
       { "params": [ "IdleSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "DisconnectedSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Disconnected" ], "type": "alias" }
      ],
      [
       { "params": [ "OtherSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Other" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$TEST$/" }
     ]
    }
   ]
  },
  {
   "title": "TEST Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_DeliveryGroupName - $tag_CatalogName $col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "CatalogName" ], "type": "tag" },
      { "params": [ "DeliveryGroupName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "LoadIndexMax" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "LoadIndexAvg" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$TEST$/" }
     ]
    }
   ]
  },
  {
   "title": "Servers Unregistered",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "Unregistered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" }
     ]
    }
   ]
  },
  {
   "title": "PROD Sessions",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "ActiveSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Active" ], "type": "alias" }
      ],
      [
       { "params": [ "IdleSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "DisconnectedSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Disconnected" ], "type": "alias" }
      ],
      [
       { "params": [ "OtherSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Other" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$PROD$/" }
     ]
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "query": "SELECT sum(\"totalsessions\") AS \"Total\" FROM \"XdWorker\" WHERE (\"sitename\" = 'AR_PROD' AND \"deliverygroupname\" = 'PRD_SCM163' OR \"deliverygroupname\" = 'PRD_SCM163_EDBOARD' OR \"deliverygroupname\" = 'PRD_SCM163_GLD') AND $timeFilter GROUP BY time(5m) fill(none)",
     "select": [
      [
       { "params": [ "TotalSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$PROD$/" }
     ]
    }
   ]
  },
  {
   "title": "PROD Load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_DeliveryGroupName - $tag_CatalogName $col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "CatalogName" ], "type": "tag" },
      { "params": [ "SiteName" ], "type": "tag" },
      { "params": [ "DeliveryGroupName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "LoadIndexMax" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "LoadIndexAvg" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$PROD$/" }
     ]
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "ActiveSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$PROD$/" }
     ]
    }
   ]
  },
  {
   "title": "Idle",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "IdleSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$PROD$/" }
     ]
    }
   ]
  },
  {
   "title": "TRAIN Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "ActiveSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Active" ], "type": "alias" }
      ],
      [
       { "params": [ "IdleSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "DisconnectedSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Disconnected" ], "type": "alias" }
      ],
      [
       { "params": [ "OtherSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Other" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$TRAIN$/" }
     ]
    }
   ]
  },
  {
   "title": "TRAIN Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_DeliveryGroupName - $tag_CatalogName $col",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "CatalogName" ], "type": "tag" },
      { "params": [ "DeliveryGroupName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "LoadIndexMax" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Max" ], "type": "alias" }
      ],
      [
       { "params": [ "LoadIndexAvg" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Avg" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$TRAIN$/" }
     ]
    }
   ]
  },
  {
   "title": "Disconnected",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "DisconnectedSessions" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$PROD$/" }
     ]
    }
   ]
  },
  {
   "title": "Unregistered",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CVADworkload",
     "select": [
      [
       { "params": [ "Unregistered" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "SiteName", "operator": "=~", "value": "/^$SiteName$/" },
      { "condition": "AND", "key": "DeliveryGroupName", "operator": "=~", "value": "/^$PROD$/" }
     ]
    }
   ]
  }
 ]
}