{
 "title": "CADC Overview",
 "tags": [
  "EUCMonitoring",
  "CADC"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "ADC",
    "label": "ADC",
    "query": "SHOW TAG VALUES WITH KEY = \"ADC\""
   },
   {
    "name": "LBvServerName",
    "query": " \tSHOW TAG VALUES FROM \"CADClbvserver\" WITH KEY = \"Name\" WHERE \"ADC\" =~ /$ADC$/ "
   },
   {
    "name": "CSvServerName",
    "query": "SHOW TAG VALUES FROM \"CADCcsvserver\" WITH KEY = \"Name\" WHERE \"ADC\" =~ /$ADC$/"
   },
   { "name": "GSLBvServerName" }
  ]
 },
 "panels": [
  {
   "title": "Total GW Users",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CADCgatewayuser",
     "select": [
      [
       { "params": [ "TotalUsers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" }
     ]
    }
   ]
  },
  {
   "title": "ICA Users",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CADCgatewayuser",
     "select": [
      [
       { "params": [ "ICAUsers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" }
     ]
    }
   ]
  },
  {
   "title": "VPN Users",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CADCgatewayuser",
     "select": [
      [
       { "params": [ "VPNUsers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" }
     ]
    }
   ]
  },
  {
   "title": "LBvServer Health",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADClbvserver",
     "select": [
      [
       { "params": [ "Health" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" }
     ]
    }
   ]
  },
  {
   "title": "LBvServer Client / Server Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADClbvserver",
     "select": [
      [
       { "params": [ "CurrentClientConnections" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Client" ], "type": "alias" }
      ],
      [
       { "params": [ "CurrentServerConnections" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Server" ], "type": "alias" }
      ],
      [
       { "params": [ "EstablishedConnections" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Established" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$LBvServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "CSvServer Health",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCcsvserver",
     "select": [
      [
       { "params": [ "Health" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$CSvServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "CSvServer Client / Server Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCcsvserver",
     "select": [
      [
       { "params": [ "CurrentClientConnections" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Client" ], "type": "alias" }
      ],
      [
       { "params": [ "CurrentServerConnections" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Server" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$CSvServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "GSLBvServer Health",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCgslbvserver",
     "select": [
      [
       { "params": [ "Health" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$GSLBvServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "GSLBvServer Client / Server Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCgslbvserver",
     "select": [
      [
       { "params": [ "CurrentClientConnections" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Client" ], "type": "alias" }
      ],
      [
       { "params": [ "CurrentServerConnections" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Server" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$GSLBvServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "Gateway Users",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCgatewayuser",
     "select": [
      [
       { "params": [ "ICAUsers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "ICA Users" ], "type": "alias" }
      ],
      [
       { "params": [ "VPNUsers" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "VPN Users" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" }
     ]
    }
   ]
  },
  {
   "title": "LB Hits / Request / Response Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $tag_Name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "Name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADClbvserver",
     "select": [
      [
       { "params": [ "HitsRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Hits" ], "type": "alias" }
      ],
      [
       { "params": [ "RequestsRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Requests" ], "type": "alias" }
      ],
      [
       { "params": [ "ResponsesRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Responses" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$LBvServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "CS Hits / Request / Response Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $tag_Name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "Name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCcsvserver",
     "select": [
      [
       { "params": [ "HitsRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Hits" ], "type": "alias" }
      ],
      [
       { "params": [ "RequestsRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Requests" ], "type": "alias" }
      ],
      [
       { "params": [ "ResponsesRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Responses" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$CSvServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "GSLB Hits / Request / Response Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $tag_Name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "Name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCgslbvserver",
     "select": [
      [
       { "params": [ "HitsRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Hits" ], "type": "alias" }
      ],
      [
       { "params": [ "RequestsRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Requests" ], "type": "alias" }
      ],
      [
       { "params": [ "ResponsesRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Responses" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$GSLBvServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "ADC System Perf",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCsystem",
     "select": [
      [
       { "params": [ "PktCpuUsagePcnt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Pkt CPU" ], "type": "alias" }
      ],
      [
       { "params": [ "MgmtCpuUsagePcnt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Mgmt CPU" ], "type": "alias" }
      ],
      [
       { "params": [ "MemUsagePcnt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Mem" ], "type": "alias" }
      ],
      [
       { "params": [ "ResCpuUsagePcnt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Res CPU" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" }
     ]
    }
   ]
  },
  {
   "title": "LB Request / Response Bytes Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $tag_Name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "Name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADClbvserver",
     "select": [
      [
       { "params": [ "RequestByteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Requests" ], "type": "alias" }
      ],
      [
       { "params": [ "ResponseByteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Responses" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$LBvServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "CS Request / Response Bytes Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $tag_Name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "Name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCcsvserver",
     "select": [
      [
       { "params": [ "RequestByteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Requests" ], "type": "alias" }
      ],
      [
       { "params": [ "ResponseByteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Responses" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$CSvServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "GSLB Request / Response Bytes Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $tag_Name $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "Name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCgslbvserver",
     "select": [
      [
       { "params": [ "RequestByteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Requests" ], "type": "alias" }
      ],
      [
       { "params": [ "ResponseByteRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Responses" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" },
      { "condition": "AND", "key": "Name", "operator": "=~", "value": "/^$GSLBvServerName$/" }
     ]
    }
   ]
  },
  {
   "title": "IP Rx/Tx Bytes Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCip",
     "select": [
      [
       { "params": [ "RxBytesRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "TxBytesRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP Rx/Tx Bytes Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCtcp",
     "select": [
      [
       { "params": [ "RxBytesRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "TxBytesRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" }
     ]
    }
   ]
  },
  {
   "title": "Certficate Expiration (days)",
   "type": "table",
   "gridPos": { "h": 10, "w": 5, "x": 8, "y": 15 },
   "targets": [
    {
     "alias": "$tag_ADC: $tag_Subject - Status $tag_Status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "Subject" ], "type": "tag" },
      { "params": [ "Status" ], "type": "tag" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CADCsslcertkey",
     "select": [
      [
       { "params": [ "DaysToExpiration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "DaysToExpiration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Hits / Miss %",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_ADC: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCcache",
     "select": [
      [
       { "params": [ "HitsPcnt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Hits" ], "type": "alias" }
      ],
      [
       { "params": [ "MissPcnt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Miss" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Gets / Posts / Others",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADChttp",
     "select": [
      [
       { "params": [ "GetsRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Gets" ], "type": "alias" }
      ],
      [
       { "params": [ "PostsRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Posts" ], "type": "alias" }
      ],
      [
       { "params": [ "OthersRate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Others" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP Req / Resp Bytes Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADChttp",
     "select": [
      [
       { "params": [ "RequestsBytesRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Request" ], "type": "alias" }
      ],
      [
       { "params": [ "ResponsesBytesRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Response" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" }
     ]
    }
   ]
  },
  {
   "title": "IP Rx/Tx Packets Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCip",
     "select": [
      [
       { "params": [ "RxPacketsRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Rx" ], "type": "alias" }
      ],
      [
       { "params": [ "TxPacketsRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Tx" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "TCP Rx/Tx Packets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCtcp",
     "select": [
      [
       { "params": [ "RxPacketsRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Rx Mbits" ], "type": "alias" }
      ],
      [
       { "params": [ "TxPacketsRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Tx Mbits" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SSL Sessions, New, Backend, Transactions Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_ADC: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ADC" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "CADCssl",
     "select": [
      [
       { "params": [ "SessionsRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Sessions" ], "type": "alias" }
      ],
      [
       { "params": [ "NewSessionsRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "New Sessions" ], "type": "alias" }
      ],
      [
       { "params": [ "BackendSessionsRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Backend Sessions" ], "type": "alias" }
      ],
      [
       { "params": [ "TransactionsRate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Transactions" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ADC", "operator": "=~", "value": "/^$ADC$/" }
     ]
    }
   ]
  }
 ]
}